Traceback (most recent call last):
  File "/Users/arturoboquin/miniconda3/envs/522_group1/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/arturoboquin/miniconda3/envs/522_group1/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arturoboquin/miniconda3/envs/522_group1/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arturoboquin/miniconda3/envs/522_group1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/arturoboquin/miniconda3/envs/522_group1/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/arturoboquin/miniconda3/envs/522_group1/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/arturoboquin/miniconda3/envs/522_group1/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# preprocessing
from DataPreprocess import *
from DataFetch import fetch_business_license, fetch_econ_indicators
from EDA import *
import pandas as pd
import numpy as np

# viz
import matplotlib.pyplot as plt
import altair as alt
alt.data_transformers.enable("vegafusion")

# reduce file size
alt.renderers.enable('svg')

#sklearn tool
from sklearn.model_selection import train_test_split
from sklearn.compose import make_column_transformer
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.model_selection import cross_validate

# models
from Modeling import transform, split_x_y
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB, BernoulliNB
from sklearn.linear_model import LogisticRegression
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;66;03m# preprocessing[39;00m
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mDataPreprocess[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mDataFetch[39;00m [38;5;28;01mimport[39;00m fetch_business_license, fetch_econ_indicators
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mEDA[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m

[0;31mModuleNotFoundError[0m: No module named 'DataPreprocess'

